import SolidCore.Spine.L00_Source.Interface
import SolidCore.Spine.L01_CheckedSolidity.Interface
import SolidCore.Spine.L02_Control.Interface
import SolidCore.Spine.L03_Effect.Interface
import SolidCore.Spine.L04_Layout.Interface
import SolidCore.Spine.L05_GeneratedYul.Interface
import SolidCore.Spine.L06_StackCfg.Interface
import SolidCore.Spine.L07_Bytecode.Interface
import SolidCore.Spine.L08_Evm.Interface
import SolidCore.Spine.Passes.P01_SourceToCheckedSolidity.Interface
import SolidCore.Spine.Passes.P02_CheckedSolidityToControl.Interface
import SolidCore.Spine.Passes.P03_ControlToEffect.Interface
import SolidCore.Spine.Passes.P04_EffectToLayout.Interface
import SolidCore.Spine.Passes.P05_LayoutToGeneratedYul.Interface
import SolidCore.Spine.Passes.P06_GeneratedYulToStackCfg.Interface
import SolidCore.Spine.Passes.P07_StackCfgToBytecode.Interface
import SolidCore.Spine.Passes.P08_BytecodeToEvm.Interface
import SolidCore.Spine.PublicClaims
